In [1]:
import rqdatac
rqdatac.init(
    username = "license",
    password = "ZZ-u7ZWosqrntc3VY3TJzJLPsb-A0o4zehYoiNpDvIBXiwvRIOUmFe7medtMhwu4qiaNxqFSc6ONdGcGeVYgUVd-w5QKScPkmzBEmYVEt94lz9sQZoHwdtQXWWRGGrJqtr7ehiQACydlPS7RcPBfJrpyeTJFsGF1E1guZbpLnvU=XouX9YSi7Pcyo0rSLCMydvHs3nrVq6Rwjda-jI9H_gfGlp53ot0ZnIA6g-ZtvwPDAb62K38pHIqYYyTAyER7FBtZ5HumXzOrWW42LHpUn5-vbnLMxiwbimJ9ns41CaMbjpFEgNcfO52l5wiqDqFCkZNy_OKSDjepfa9GxHsLZZE="
)
from rqdatac import *
import pandas as pd
import numpy as np
import pickle
import os

d:\Ana\envs\rqsdk\lib\site-packages\rqdatac\client.py:263: UserWarning: Your account will be expired after  29 days. Please call us at 0755-22676337 to upgrade or purchase or renew your contract.
  warnings.warn("Your account will be expired after  {} days. "

提取股指分红信息

In [26]:
#财务信息
get_pit_financials_ex('600030.XSHG', ["net_profit","basic_earnings_per_share","fully_diluted_earnings_per_share"], start_quarter="2023q4", end_quarter="2025q4", date=None, statements='latest', market='cn')

                       info_date  fully_diluted_earnings_per_share  \
order_book_id quarter
600030.XSHG   2023q4  2026-03-27                              1.30
              2024q1  2025-04-30                              0.32
              2024q2  2025-08-29                              0.69
              2024q3  2025-10-25                              1.09
              2024q4  2026-03-27                              1.41
              2025q1  2026-04-25                              0.43
              2025q2  2025-08-29                              0.89
              2025q3  2025-10-25                              1.51
              2025q4  2026-04-25                              1.96

                         net_profit  basic_earnings_per_share  if_adjusted  \
order_book_id quarter
600030.XSHG   2023q4   2.053935e+10                      1.30            1
              2024q1   5.162144e+09                      0.32            1
              2024q2   1.098194e+10                      0.69            1
              2024q3   1.745091e+10                      1.09            1
              2024q4   2.258946e+10                      1.41            1
              2025q1   6.824725e+09                      0.43            1
              2025q2   1.414623e+10                      0.89            0
              2025q3   2.391562e+10                      1.51            0
              2025q4   3.100668e+10                      1.96            1

                           rice_create_tm
order_book_id quarter
600030.XSHG   2023q4  2026-03-27 04:14:32
              2024q1  2025-04-29 20:21:27
              2024q2  2025-08-28 20:20:16
              2024q3  2025-10-24 20:14:20
              2024q4  2026-03-26 20:13:16
              2025q1  2026-04-24 20:14:24
              2025q2  2025-08-28 20:20:16
              2025q3  2025-10-24 20:14:20
              2025q4  2026-04-24 20:14:24

In [ ]:
get_dividend_info('000001.XSHE', start_date="20250101", end_date="20251231", market='cn') #STRP1

,order_book_id,info_date,ex_dividend_date,dividend_bonus_share,dividend_transferred_share,dividend_cash_before_tax,dividend_type,sequence_num,special_dividend,rice_create_tm
effective_date,,,,,,,,,,
2025-06-30,000001.XSHE,2025-09-30,2025-10-15,NaN,NaN,2.36,cash only,1,False,2026-02-02 12:26:09
2025-12-31,000001.XSHE,2026-06-05,2026-06-12,NaN,NaN,3.60,cash only,1,False,2026-06-05 08:13:18

In [48]:
get_dividend('600030.XSHG', start_date="20240101", end_date="20261231", expect_df=True, market='cn')

                                            book_closure_date  \
order_book_id declaration_announcement_date
600030.XSHG   2024-08-16                           2024-08-23
              2024-12-14                           2024-12-19
              2025-08-19                           2025-08-22
              2026-02-03                           2026-02-06
              2026-06-04                           2026-06-09

                                             dividend_cash_before_tax  \
order_book_id declaration_announcement_date
600030.XSHG   2024-08-16                                         4.75
              2024-12-14                                         2.40
              2025-08-19                                         2.80
              2026-02-03                                         2.90
              2026-06-04                                         4.10

                                            ex_dividend_date payable_date  \
order_book_id declaration_announcement_date
600030.XSHG   2024-08-16                          2024-08-26   2024-08-26
              2024-12-14                          2024-12-20   2024-12-20
              2025-08-19                          2025-08-25   2025-08-25
              2026-02-03                          2026-02-09   2026-02-09
              2026-06-04                          2026-06-10   2026-06-10

                                            advance_date  round_lot quarter
order_book_id declaration_announcement_date
600030.XSHG   2024-08-16                      2024-03-27         10  2023q4
              2024-12-14                      2024-08-29         10  2024q2
              2025-08-19                      2025-03-27         10  2024q4
              2026-02-03                      2025-08-29         10  2025q2
              2026-06-04                      2026-03-27         10  2025q4

In [ ]:
#好像普遍是2023年分红1次，2024年及以后分红2次【优秀的股票】
3.60 /10 / 2.07 #0.17391304347826086
3.62 /10 /2.15 #0.16837209302325581
7.19/10/2.25 #0.3195555555555556

4.10/10 /1.96 #0.20918367346938774
2.80/10/1.41 #0.19858156028368792
4.75/10/1.30 #0.36538461538461536

#单独看一下年中分红的比例
2.90/10/0.89 #0.32584269662921345
2.40/10/0.69 #0.34782608695652173

0.32584269662921345

In [32]:
get_dividend_amount('000001.XSHE', start_quarter = "2022q4", end_quarter = "2025q4", date = None, market = 'cn')

                      event_procedure  info_date        amount  \
order_book_id quarter
000001.XSHE   2022q4               预案 2023-03-09  5.530687e+09
              2022q4               决案 2023-06-01  5.530687e+09
              2022q4             方案实施 2023-06-07  5.530687e+09
              2023q4               预案 2024-03-15  1.395286e+10
              2023q4               决案 2024-05-25  1.395286e+10
              2023q4             方案实施 2024-06-06  1.395286e+10
              2024q2               预案 2024-08-16  4.773856e+09
              2024q2             方案实施 2024-09-26  4.773856e+09
              2024q4               预案 2025-03-15  7.025000e+09
              2024q4               决案 2025-05-24  7.025000e+09
              2024q4             方案实施 2025-06-05  7.025000e+09
              2025q2               预案 2025-08-23  4.580000e+09
              2025q2             方案实施 2025-09-30  4.580000e+09
              2025q4               预案 2026-03-21  6.986000e+09
              2025q4               决案 2026-05-23  6.986000e+09
              2025q4             方案实施 2026-06-05  6.986131e+09

                           rice_create_tm
order_book_id quarter
000001.XSHE   2022q4  2024-06-11 18:13:11
              2022q4  2024-06-11 18:13:11
              2022q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2024q2  2024-08-16 08:14:04
              2024q2  2024-09-25 20:14:07
              2024q4  2025-03-14 20:14:03
              2024q4  2025-05-24 08:14:12
              2024q4  2025-06-04 20:14:02
              2025q2  2025-08-22 20:14:09
              2025q2  2025-09-30 08:14:11
              2025q4  2026-03-21 08:14:03
              2025q4  2026-05-23 08:14:15
              2025q4  2026-06-05 08:14:17

In [46]:
#系统提取财务信息
import pandas as pd
srcdir = "E:/SJTU/intern/gtht/barra/data_base/index_component_日频"

df = pd.read_pickle(f"{srcdir}/866011.RI_20_26D_dict.pkl")
ids = list(df.values())[-1].index.tolist()
df_eps = get_pit_financials_ex(ids,  ["basic_earnings_per_share"], start_quarter="2024q1", end_quarter="2025q4", date=None, statements='latest', market='cn')
df_eps

                       info_date  basic_earnings_per_share  if_adjusted  \
order_book_id quarter
000001.XSHE   2024q1  2025-04-19                      0.66            1
              2024q2  2025-10-25                      1.23            1
              2024q3  2025-10-25                      1.94            1
              2024q4  2026-03-21                      2.15            1
              2025q1  2026-04-25                      0.62            1
...                          ...                       ...          ...
689009.XSHG   2024q4  2026-03-31                     15.32            1
              2025q1  2026-04-30                      6.36            1
              2025q2  2025-10-25                     17.29            0
              2025q3  2025-10-25                     25.05            0
              2025q4  2026-04-30                     24.72            1

                           rice_create_tm
order_book_id quarter
000001.XSHE   2024q1  2025-04-18 20:11:59
              2024q2  2025-10-24 20:11:51
              2024q3  2025-10-24 20:11:51
              2024q4  2026-03-21 04:12:50
              2025q1  2026-04-24 20:12:51
...                                   ...
689009.XSHG   2024q4  2026-03-31 04:17:45
              2025q1  2026-04-29 20:26:33
              2025q2  2025-10-24 20:15:49
              2025q3  2025-10-24 20:15:49
              2025q4  2026-04-29 20:26:33

[41583 rows x 4 columns]

In [47]:
desdir = "E:/SJTU/intern/gtht/barra/data_base/basis"
df_eps.to_pickle(f"{desdir}/866011.RI_eps_24_25Q.pkl")

In [73]:
#系统提取分红数据
df_dps = get_dividend(ids, start_date="20240630", end_date="20261231", expect_df=True, market='cn')
df_dps.to_pickle(f"{desdir}/866011.RI_dps_24_25Q.pkl")
df_dps

                                            book_closure_date  \
order_book_id declaration_announcement_date
000001.XSHE   2024-09-26                           2024-10-09
              2025-06-05                           2025-06-11
              2025-09-30                           2025-10-14
              2026-06-05                           2026-06-11
000009.XSHE   2024-07-19                           2024-07-25
...                                                       ...
688816.XSHG   2026-05-22                           2026-05-27
688819.XSHG   2025-06-06                           2025-06-12
              2026-06-05                           2026-06-10
689009.XSHG   2025-06-07                           2025-06-12
              2025-10-25                           2025-10-30

                                             dividend_cash_before_tax  \
order_book_id declaration_announcement_date
000001.XSHE   2024-09-26                                        2.460
              2025-06-05                                        3.620
              2025-09-30                                        2.360
              2026-06-05                                        3.600
000009.XSHE   2024-07-19                                        0.450
...                                                               ...
688816.XSHG   2026-05-22                                        2.400
688819.XSHG   2025-06-06                                        4.100
              2026-06-05                                        5.500
689009.XSHG   2025-06-07                                      113.100
              2025-10-25                                       42.073

                                            ex_dividend_date payable_date  \
order_book_id declaration_announcement_date
000001.XSHE   2024-09-26                          2024-10-10   2024-10-10
              2025-06-05                          2025-06-12   2025-06-12
              2025-09-30                          2025-10-15   2025-10-15
              2026-06-05                          2026-06-12   2026-06-12
000009.XSHE   2024-07-19                          2024-07-26   2024-07-26
...                                                      ...          ...
688816.XSHG   2026-05-22                          2026-05-28   2026-05-28
688819.XSHG   2025-06-06                          2025-06-13   2025-06-13
              2026-06-05                          2026-06-11   2026-06-11
689009.XSHG   2025-06-07                          2025-06-13   2025-06-13
              2025-10-25                          2025-10-31   2025-10-31

                                            advance_date  round_lot quarter
order_book_id declaration_announcement_date
000001.XSHE   2024-09-26                      2024-08-16         10  2024q2
              2025-06-05                      2025-03-15         10  2024q4
              2025-09-30                      2025-08-23         10  2025q2
              2026-06-05                      2026-03-21         10  2025q4
000009.XSHE   2024-07-19                      2024-04-16         10  2023q4
...                                                  ...        ...     ...
688816.XSHG   2026-05-22                      2026-04-18         10  2025q4
688819.XSHG   2025-06-06                      2025-03-28         10  2024q4
              2026-06-05                      2026-03-28         10  2025q4
689009.XSHG   2025-06-07                      2025-04-12         10  2024q4
              2025-10-25                      2025-08-02         10  2025q2

[9291 rows x 7 columns]

In [74]:
df_time = get_dividend_amount(ids, start_quarter = "2024q2", end_quarter = "2025q4", date = None, market = 'cn')
df_time.to_pickle(f"{desdir}/dividend_timeline.pkl")
df_time

                      event_procedure  info_date        amount  \
order_book_id quarter
000001.XSHE   2024q2               预案 2024-08-16  4.773856e+09
              2024q2             方案实施 2024-09-26  4.773856e+09
              2024q4               预案 2025-03-15  7.025000e+09
              2024q4               决案 2025-05-24  7.025000e+09
              2024q4             方案实施 2025-06-05  7.025000e+09
...                               ...        ...           ...
689009.XSHG   2025q2               预案 2025-08-02  3.003448e+08
              2025q2               决案 2025-10-10  3.003448e+08
              2025q2             方案实施 2025-10-25  3.003448e+08
              2025q4               预案 2026-03-31  9.000661e+08
              2025q4               决案 2026-06-27  9.000661e+08

                           rice_create_tm
order_book_id quarter
000001.XSHE   2024q2  2024-08-16 08:14:04
              2024q2  2024-09-25 20:14:07
              2024q4  2025-03-14 20:14:03
              2024q4  2025-05-24 08:14:12
              2024q4  2025-06-04 20:14:02
...                                   ...
689009.XSHG   2025q2  2025-08-01 20:14:08
              2025q2  2025-10-09 20:14:12
              2025q2  2025-10-24 20:14:04
              2025q4  2026-03-31 08:14:05
              2025q4  2026-06-27 08:14:15

[25774 rows x 4 columns]