In [4]:
import rqdatac
rqdatac.init(
    username = "license",
    password = "ZZ-u7ZWosqrntc3VY3TJzJLPsb-A0o4zehYoiNpDvIBXiwvRIOUmFe7medtMhwu4qiaNxqFSc6ONdGcGeVYgUVd-w5QKScPkmzBEmYVEt94lz9sQZoHwdtQXWWRGGrJqtr7ehiQACydlPS7RcPBfJrpyeTJFsGF1E1guZbpLnvU=XouX9YSi7Pcyo0rSLCMydvHs3nrVq6Rwjda-jI9H_gfGlp53ot0ZnIA6g-ZtvwPDAb62K38pHIqYYyTAyER7FBtZ5HumXzOrWW42LHpUn5-vbnLMxiwbimJ9ns41CaMbjpFEgNcfO52l5wiqDqFCkZNy_OKSDjepfa9GxHsLZZE="
)
from rqdatac import *
import pandas as pd
import numpy as np
import pickle
import os

d:\Ana\envs\rqsdk\lib\site-packages\rqdatac\client.py:263: UserWarning: Your account will be expired after  32 days. Please call us at 0755-22676337 to upgrade or purchase or renew your contract.
  warnings.warn("Your account will be expired after  {} days. "

提取股指分红信息

In [16]:
#财务信息
get_pit_financials_ex('600873.XSHG', ["net_profit","basic_earnings_per_share","fully_diluted_earnings_per_share"], start_quarter="2023q4", end_quarter="2025q4", date=None, statements='latest', market='cn')

                       info_date    net_profit  basic_earnings_per_share  \
order_book_id quarter
600873.XSHG   2023q4  2026-04-22  3.180950e+09                      1.06
              2024q1  2025-04-22  7.517046e+08                      0.26
              2024q2  2025-08-20  1.473824e+09                      0.50
              2024q3  2025-10-30  1.995322e+09                      0.68
              2024q4  2026-04-22  2.740427e+09                      0.94
              2025q1  2026-04-22  1.018706e+09                      0.36
              2025q2  2025-08-20  1.767950e+09                      0.62
              2025q3  2025-10-30  3.025092e+09                      1.06
              2025q4  2026-04-22  3.280880e+09                      1.17

                       fully_diluted_earnings_per_share  if_adjusted  \
order_book_id quarter
600873.XSHG   2023q4                               1.06            1
              2024q1                               0.26            1
              2024q2                               0.50            1
              2024q3                               0.68            1
              2024q4                               0.94            1
              2025q1                               0.36            1
              2025q2                               0.62            0
              2025q3                               1.06            0
              2025q4                               1.17            0

                           rice_create_tm
order_book_id quarter
600873.XSHG   2023q4  2026-04-21 20:18:44
              2024q1  2025-04-21 20:13:05
              2024q2  2025-08-19 20:12:49
              2024q3  2025-10-29 20:17:39
              2024q4  2026-04-21 20:18:44
              2025q1  2026-04-21 20:18:44
              2025q2  2025-08-19 20:12:49
              2025q3  2025-10-29 20:17:39
              2025q4  2026-04-21 20:18:44

In [ ]:
get_dividend_info('000001.XSHE', start_date="20250101", end_date="20251231", market='cn') #STRP1

,order_book_id,info_date,ex_dividend_date,dividend_bonus_share,dividend_transferred_share,dividend_cash_before_tax,dividend_type,sequence_num,special_dividend,rice_create_tm
effective_date,,,,,,,,,,
2025-06-30,000001.XSHE,2025-09-30,2025-10-15,NaN,NaN,2.36,cash only,1,False,2026-02-02 12:26:09
2025-12-31,000001.XSHE,2026-06-05,2026-06-12,NaN,NaN,3.60,cash only,1,False,2026-06-05 08:13:18

In [3]:
get_dividend("000001.XSHE", start_date="20220630", end_date="20261231", expect_df=True, market='cn') #日期参数针对于declaration_announcement_date #'600030.XSHG'

                                             dividend_cash_before_tax  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                                         2.28
              2023-06-07                                         2.85
              2024-06-06                                         7.19
              2024-09-26                                         2.46
              2025-06-05                                         3.62
              2025-09-30                                         2.36
              2026-06-05                                         3.60

                                            book_closure_date  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                           2022-07-21
              2023-06-07                           2023-06-13
              2024-06-06                           2024-06-13
              2024-09-26                           2024-10-09
              2025-06-05                           2025-06-11
              2025-09-30                           2025-10-14
              2026-06-05                           2026-06-11

                                            ex_dividend_date payable_date  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                          2022-07-22   2022-07-22
              2023-06-07                          2023-06-14   2023-06-14
              2024-06-06                          2024-06-14   2024-06-14
              2024-09-26                          2024-10-10   2024-10-10
              2025-06-05                          2025-06-12   2025-06-12
              2025-09-30                          2025-10-15   2025-10-15
              2026-06-05                          2026-06-12   2026-06-12

                                             round_lot advance_date quarter
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                            10   2022-03-10  2021q4
              2023-06-07                            10   2023-03-09  2022q4
              2024-06-06                            10   2024-03-15  2023q4
              2024-09-26                            10   2024-08-16  2024q2
              2025-06-05                            10   2025-03-15  2024q4
              2025-09-30                            10   2025-08-23  2025q2
              2026-06-05                            10   2026-03-21  2025q4

In [2]:
get_dividend_amount("000001.XSHE", start_quarter = "2020q2", end_quarter = "2026q2", date = None, market = 'cn')

                      event_procedure  info_date        amount  \
order_book_id quarter
000001.XSHE   2020q4               预案 2021-02-02  3.493000e+09
              2020q4               决案 2021-04-09  3.493000e+09
              2020q4             方案实施 2021-05-07  3.493065e+09
              2021q4               预案 2022-03-10  4.425000e+09
              2021q4               决案 2022-06-29  4.425000e+09
              2021q4             方案实施 2022-07-15  4.424549e+09
              2022q4               预案 2023-03-09  5.530687e+09
              2022q4               决案 2023-06-01  5.530687e+09
              2022q4             方案实施 2023-06-07  5.530687e+09
              2023q4               预案 2024-03-15  1.395286e+10
              2023q4               决案 2024-05-25  1.395286e+10
              2023q4             方案实施 2024-06-06  1.395286e+10
              2024q2               预案 2024-08-16  4.773856e+09
              2024q2             方案实施 2024-09-26  4.773856e+09
              2024q4               预案 2025-03-15  7.025000e+09
              2024q4               决案 2025-05-24  7.025000e+09
              2024q4             方案实施 2025-06-05  7.025000e+09
              2025q2               预案 2025-08-23  4.580000e+09
              2025q2             方案实施 2025-09-30  4.580000e+09
              2025q4               预案 2026-03-21  6.986000e+09
              2025q4               决案 2026-05-23  6.986000e+09
              2025q4             方案实施 2026-06-05  6.986131e+09

                           rice_create_tm
order_book_id quarter
000001.XSHE   2020q4  2024-06-11 18:13:11
              2020q4  2024-06-11 18:13:11
              2020q4  2024-06-11 18:13:11
              2021q4  2024-06-11 18:13:11
              2021q4  2024-06-11 18:13:11
              2021q4  2024-06-11 18:13:11
              2022q4  2024-06-11 18:13:11
              2022q4  2024-06-11 18:13:11
              2022q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2023q4  2024-06-11 18:13:11
              2024q2  2024-08-16 08:14:04
              2024q2  2024-09-25 20:14:07
              2024q4  2025-03-14 20:14:03
              2024q4  2025-05-24 08:14:12
              2024q4  2025-06-04 20:14:02
              2025q2  2025-08-22 20:14:09
              2025q2  2025-09-30 08:14:11
              2025q4  2026-03-21 08:14:03
              2025q4  2026-05-23 08:14:15
              2025q4  2026-06-05 08:14:17

In [18]:
#好像普遍是2023年分红1次，2024年及以后分红2次【优秀的股票】
3.60 /10 / 2.07 #0.17391304347826086
3.62 /10 /2.15 #0.16837209302325581
7.19/10/2.25 #0.3195555555555556

4.10/10 /1.96 #0.20918367346938774
2.80/10/1.41 #0.19858156028368792
4.75/10/1.30 #0.36538461538461536

#单独看一下年中分红的比例
2.90/10/0.89 #0.32584269662921345
2.40/10/0.69 #0.34782608695652173

6.076424e+09 / 3.100668e+10	

77376418.95 / 1.350317e+09 #0.05730241043399439

#平安银行测算
2.07 * (6986130551.28 / 42633000000.0)*0.9  #0.3392041432962634  vs
3.6 / 10 * 0.90 #0.324

#九号公式测算
900066128.78 / 1762310096.9 #0.5！

#梅花生物测算
1.17 * 1199935002.04 / 3280879912.1

0.4279108013704126

In [29]:
#系统提取财务信息
import pandas as pd
srcdir = "E:/SJTU/intern/gtht/barra/data_base/index_component_日频"

df = pd.read_pickle(f"{srcdir}/866011.RI_20_26D_dict.pkl")
ids = list(df.values())[-1].index.tolist()
df_eps = get_pit_financials_ex(ids,  ["basic_earnings_per_share","net_profit"], start_quarter="2024q1", end_quarter="2025q4", date=None, statements='latest', market='cn')
df_eps

                       info_date      rice_create_tm  if_adjusted  \
order_book_id quarter
000001.XSHE   2024q1  2025-04-19 2025-04-18 20:11:59            1
              2024q2  2025-10-25 2025-10-24 20:11:51            1
              2024q3  2025-10-25 2025-10-24 20:11:51            1
              2024q4  2026-03-21 2026-03-21 04:12:50            1
              2025q1  2026-04-25 2026-04-24 20:12:51            1
...                          ...                 ...          ...
689009.XSHG   2024q4  2026-03-31 2026-03-31 04:17:45            1
              2025q1  2026-04-30 2026-04-29 20:26:33            1
              2025q2  2025-10-25 2025-10-24 20:15:49            0
              2025q3  2025-10-25 2025-10-24 20:15:49            0
              2025q4  2026-04-30 2026-04-29 20:26:33            1

                       basic_earnings_per_share    net_profit
order_book_id quarter
000001.XSHE   2024q1                       0.66  1.493200e+10
              2024q2                       1.23  2.587900e+10
              2024q3                       1.94  3.972900e+10
              2024q4                       2.15  4.450800e+10
              2025q1                       0.62  1.409600e+10
...                                         ...           ...
689009.XSHG   2024q4                      15.32  1.085276e+09
              2025q1                       6.36  4.558939e+08
              2025q2                      17.29  1.251669e+09
              2025q3                      25.05  1.749687e+09
              2025q4                      24.72  1.762310e+09

[41583 rows x 5 columns]

In [30]:
desdir = "E:/SJTU/intern/gtht/barra/data_base/basis"
df_eps.to_pickle(f"{desdir}/866011.RI_eps_24_25Q.pkl")

In [31]:
df_eps = pd.read_pickle(f"{desdir}/866011.RI_eps_24_25Q.pkl")
df_eps

                       info_date      rice_create_tm  if_adjusted  \
order_book_id quarter
000001.XSHE   2024q1  2025-04-19 2025-04-18 20:11:59            1
              2024q2  2025-10-25 2025-10-24 20:11:51            1
              2024q3  2025-10-25 2025-10-24 20:11:51            1
              2024q4  2026-03-21 2026-03-21 04:12:50            1
              2025q1  2026-04-25 2026-04-24 20:12:51            1
...                          ...                 ...          ...
689009.XSHG   2024q4  2026-03-31 2026-03-31 04:17:45            1
              2025q1  2026-04-30 2026-04-29 20:26:33            1
              2025q2  2025-10-25 2025-10-24 20:15:49            0
              2025q3  2025-10-25 2025-10-24 20:15:49            0
              2025q4  2026-04-30 2026-04-29 20:26:33            1

                       basic_earnings_per_share    net_profit
order_book_id quarter
000001.XSHE   2024q1                       0.66  1.493200e+10
              2024q2                       1.23  2.587900e+10
              2024q3                       1.94  3.972900e+10
              2024q4                       2.15  4.450800e+10
              2025q1                       0.62  1.409600e+10
...                                         ...           ...
689009.XSHG   2024q4                      15.32  1.085276e+09
              2025q1                       6.36  4.558939e+08
              2025q2                      17.29  1.251669e+09
              2025q3                      25.05  1.749687e+09
              2025q4                      24.72  1.762310e+09

[41583 rows x 5 columns]

In [31]:
#系统提取分红数据
srcdir = "E:/SJTU/intern/gtht/barra/data_base/index_component_日频"

df = pd.read_pickle(f"{srcdir}/866011.RI_20_26D_dict.pkl")
ids = list(df.values())[-1].index.tolist()
df_dps = get_dividend(ids, start_date="20220630", end_date="20261231", expect_df=True, market='cn')
df_dps.to_pickle(f"{desdir}/866011.RI_dps_22_25H.pkl")
df_dps

                                             dividend_cash_before_tax  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                                        2.280
              2023-06-07                                        2.850
              2024-06-06                                        7.190
              2024-09-26                                        2.460
              2025-06-05                                        3.620
...                                                               ...
688819.XSHG   2025-06-06                                        4.100
              2026-06-05                                        5.500
689009.XSHG   2024-05-18                                       28.350
              2025-06-07                                      113.100
              2025-10-25                                       42.073

                                            book_closure_date  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                           2022-07-21
              2023-06-07                           2023-06-13
              2024-06-06                           2024-06-13
              2024-09-26                           2024-10-09
              2025-06-05                           2025-06-11
...                                                       ...
688819.XSHG   2025-06-06                           2025-06-12
              2026-06-05                           2026-06-10
689009.XSHG   2024-05-18                           2024-05-23
              2025-06-07                           2025-06-12
              2025-10-25                           2025-10-30

                                            ex_dividend_date payable_date  \
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                          2022-07-22   2022-07-22
              2023-06-07                          2023-06-14   2023-06-14
              2024-06-06                          2024-06-14   2024-06-14
              2024-09-26                          2024-10-10   2024-10-10
              2025-06-05                          2025-06-12   2025-06-12
...                                                      ...          ...
688819.XSHG   2025-06-06                          2025-06-13   2025-06-13
              2026-06-05                          2026-06-11   2026-06-11
689009.XSHG   2024-05-18                          2024-05-24   2024-05-24
              2025-06-07                          2025-06-13   2025-06-13
              2025-10-25                          2025-10-31   2025-10-31

                                             round_lot advance_date quarter
order_book_id declaration_announcement_date
000001.XSHE   2022-07-15                            10   2022-03-10  2021q4
              2023-06-07                            10   2023-03-09  2022q4
              2024-06-06                            10   2024-03-15  2023q4
              2024-09-26                            10   2024-08-16  2024q2
              2025-06-05                            10   2025-03-15  2024q4
...                                                ...          ...     ...
688819.XSHG   2025-06-06                            10   2025-03-28  2024q4
              2026-06-05                            10   2026-03-28  2025q4
689009.XSHG   2024-05-18                            10   2024-04-02  2023q4
              2025-06-07                            10   2025-04-12  2024q4
              2025-10-25                            10   2025-08-02  2025q2

[16698 rows x 7 columns]

In [ ]:
#系统更新时间线
df_time = get_dividend_amount(ids, start_quarter = "2024q2", end_quarter = "2025q4", date = None, market = 'cn')
df_time.to_pickle(f"{desdir}/dividend_timeline.pkl")
df_time

                      event_procedure  info_date        amount  \
order_book_id quarter
000001.XSHE   2024q2               预案 2024-08-16  4.773856e+09
              2024q2             方案实施 2024-09-26  4.773856e+09
              2024q4               预案 2025-03-15  7.025000e+09
              2024q4               决案 2025-05-24  7.025000e+09
              2024q4             方案实施 2025-06-05  7.025000e+09
...                               ...        ...           ...
689009.XSHG   2025q2               预案 2025-08-02  3.003448e+08
              2025q2               决案 2025-10-10  3.003448e+08
              2025q2             方案实施 2025-10-25  3.003448e+08
              2025q4               预案 2026-03-31  9.000661e+08
              2025q4               决案 2026-06-27  9.000661e+08

                           rice_create_tm
order_book_id quarter
000001.XSHE   2024q2  2024-08-16 08:14:04
              2024q2  2024-09-25 20:14:07
              2024q4  2025-03-14 20:14:03
              2024q4  2025-05-24 08:14:12
              2024q4  2025-06-04 20:14:02
...                                   ...
689009.XSHG   2025q2  2025-08-01 20:14:08
              2025q2  2025-10-09 20:14:12
              2025q2  2025-10-24 20:14:04
              2025q4  2026-03-31 08:14:05
              2025q4  2026-06-27 08:14:15

[25774 rows x 4 columns]

In [9]:
get_price(["000016.XSHG","000300.XSHG", "000905.XSHG","000852.XSHG"], start_date="20260703", end_date="20260703", frequency='1d', fields=["close"], adjust_type='pre', skip_suspended=False, expect_df=True, time_slice=None, market='cn')

                              close
order_book_id date
000016.XSHG   2026-07-03  2931.2835
000300.XSHG   2026-07-03  4842.1737
000905.XSHG   2026-07-03  8745.2607
000852.XSHG   2026-07-03  8620.7886

In [23]:
alldir = os.path.join(r"E:\SJTU\intern\gtht\barra\data_base\index_component_日频", "866011.RI_20_26D_dict.pkl")
all_df = pd.read_pickle(alldir)
all_df

{Timestamp('2020-01-02 00:00:00'): order_book_id
 000001.XSHE    0.006719
 000002.XSHE    0.008876
 000004.XSHE    0.000051
 000005.XSHE    0.000109
 000006.XSHE    0.000196
                  ...
 688368.XSHG    0.000052
 688369.XSHG    0.000045
 688388.XSHG    0.000128
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3753, dtype: float64,
 Timestamp('2020-01-03 00:00:00'): order_book_id
 000001.XSHE    0.006829
 000002.XSHE    0.008719
 000004.XSHE    0.000051
 000005.XSHE    0.000109
 000006.XSHE    0.000199
                  ...
 688368.XSHG    0.000050
 688369.XSHG    0.000045
 688388.XSHG    0.000124
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3754, dtype: float64,
 Timestamp('2020-01-06 00:00:00'): order_book_id
 000001.XSHE    0.006768
 000002.XSHE    0.008551
 000004.XSHE    0.000050
 000005.XSHE    0.000109
 000006.XSHE    0.000197
                  ...
 688368.XSHG    0.000051
 688369.XSHG    0.000045
 688388.XSHG    0.000132
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3755, dtype: float64,
 Timestamp('2020-01-07 00:00:00'): order_book_id
 000001.XSHE    0.006730
 000002.XSHE    0.008530
 000004.XSHE    0.000050
 000005.XSHE    0.000110
 000006.XSHE    0.000196
                  ...
 688368.XSHG    0.000051
 688369.XSHG    0.000046
 688388.XSHG    0.000129
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3755, dtype: float64,
 Timestamp('2020-01-08 00:00:00'): order_book_id
 000001.XSHE    0.006617
 000002.XSHE    0.008613
 000004.XSHE    0.000050
 000005.XSHE    0.000109
 000006.XSHE    0.000195
                  ...
 688368.XSHG    0.000052
 688369.XSHG    0.000046
 688388.XSHG    0.000131
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3755, dtype: float64,
 Timestamp('2020-01-09 00:00:00'): order_book_id
 000001.XSHE    0.006573
 000002.XSHE    0.008628
 000004.XSHE    0.000050
 000005.XSHE    0.000110
 000006.XSHE    0.000195
                  ...
 688368.XSHG    0.000053
 688369.XSHG    0.000047
 688388.XSHG    0.000130
 688389.XSHG    0.000025
 688399.XSHG    0.000033
 Name: weight, Length: 3756, dtype: float64,
 Timestamp('2020-01-10 00:00:00'): order_book_id
 000001.XSHE    0.006541
 000002.XSHE    0.008440
 000004.XSHE    0.000050
 000005.XSHE    0.000108
 000006.XSHE    0.000195
                  ...
 688368.XSHG    0.000053
 688369.XSHG    0.000047
 688388.XSHG    0.000127
 688389.XSHG    0.000026
 688399.XSHG    0.000034
 Name: weight, Length: 3757, dtype: float64,
 Timestamp('2020-01-13 00:00:00'): order_book_id
 000001.XSHE    0.006583
 000002.XSHE    0.008401
 000004.XSHE    0.000051
 000005.XSHE    0.000107
 000006.XSHE    0.000195
                  ...
 688368.XSHG    0.000052
 688369.XSHG    0.000047
 688388.XSHG    0.000129
 688389.XSHG    0.000026
 688399.XSHG    0.000033
 Name: weight, Length: 3759, dtype: float64,
 Timestamp('2020-01-14 00:00:00'): order_book_id
 000001.XSHE    0.006510
 000002.XSHE    0.008345
 000004.XSHE    0.000052
 000005.XSHE    0.000109
 000006.XSHE    0.000195
                  ...
 688368.XSHG    0.000052
 688369.XSHG    0.000047
 688388.XSHG    0.000135
 688389.XSHG    0.000026
 688399.XSHG    0.000035
 Name: weight, Length: 3760, dtype: float64,
 Timestamp('2020-01-15 00:00:00'): order_book_id
 000001.XSHE    0.006439
 000002.XSHE    0.008134
 000004.XSHE    0.000051
 000005.XSHE    0.000108
 000006.XSHE    0.000194
                  ...
 688368.XSHG    0.000051
 688369.XSHG    0.000047
 688388.XSHG    0.000132
 688389.XSHG    0.000026
 688399.XSHG    0.000035
 Name: weight, Length: 3760, dtype: float64,
 Timestamp('2020-01-16 00:00:00'): order_book_id
 000001.XSHE    0.006378
 000002.XSHE    0.008162
 000004.XSHE    0.000051
 000005.XSHE    0.000107
 000006.XSHE    0.000192
                  ...
 688368.XSHG    0.000054
 688369.XSHG    0.000048
 688388.XSHG    0.000133
 688389.XSHG    0.000026
 688399.XSHG    0.000035
 Name: weight, Length: 3760, dtype: float64,
 Timestamp('2020-01-17 00:00:00'): order_book_id
 000001.XSHE    0.006405
 000002.XSHE    0.008147
 000004.XSHE    0.000050
 000005.XSHE    0.000107
 000006.XSHE    0.000191
                  ...
 688368.XSHG    0.000057
 688369.XSHG    0.000050
 688388.XSHG    0.000138
 688389.XSHG    0.000027
 688399.XSHG    0.000036
 Name: weight, Length: 3763, dtype: float64,
 Timestamp('2020-01-20 00:00:00'): order_book_id
 000001.XSHE    0.006352
 000002.XSHE    0.007894
 000004.XSHE    0.000056
 000005.XSHE    0.000106
 000006.XSHE    0.000189
                  ...
 688368.XSHG    0.000068
 688369.XSHG    0.000050
 688388.XSHG    0.000133
 688389.XSHG    0.000029
 688399.XSHG    0.000043
 Name: weight, Length: 3763, dtype: float64,
 Timestamp('2020-01-21 00:00:00'): order_book_id
 000001.XSHE    0.006269
 000002.XSHE    0.007834
 000004.XSHE    0.000057
 000005.XSHE    0.000104
 000006.XSHE    0.000187
                  ...
 688368.XSHG    0.000061
 688369.XSHG    0.000049
 688388.XSHG    0.000126
 688389.XSHG    0.000029
 688399.XSHG    0.000052
 Name: weight, Length: 3763, dtype: float64,
 Timestamp('2020-01-22 00:00:00'): order_book_id
 000001.XSHE    0.006269
 000002.XSHE    0.008030
 000004.XSHE    0.000057
 000005.XSHE    0.000104
 000006.XSHE    0.000187
                  ...
 688368.XSHG    0.000068
 688369.XSHG    0.000050
 688388.XSHG    0.000137
 688389.XSHG    0.000028
 688399.XSHG    0.000049
 Name: weight, Length: 3764, dtype: float64,
 Timestamp('2020-01-23 00:00:00'): order_book_id
 000001.XSHE    0.006257
 000002.XSHE    0.007986
 000004.XSHE    0.000057
 000005.XSHE    0.000104
 000006.XSHE    0.000187
                  ...
 688368.XSHG    0.000070
 688369.XSHG    0.000048
 688388.XSHG    0.000140
 688389.XSHG    0.000028
 688399.XSHG    0.000056
 Name: weight, Length: 3764, dtype: float64,
 Timestamp('2020-02-03 00:00:00'): order_book_id
 000001.XSHE    0.006131
 000002.XSHE    0.007988
 000004.XSHE    0.000056
 000005.XSHE    0.000102
 000006.XSHE    0.000183
                  ...
 688368.XSHG    0.000061
 688369.XSHG    0.000054
 688388.XSHG    0.000137
 688389.XSHG    0.000036
 688399.XSHG    0.000073
 Name: weight, Length: 3765, dtype: float64,
 Timestamp('2020-02-04 00:00:00'): order_book_id
 000001.XSHE    0.006286
 000002.XSHE    0.008139
 000004.XSHE    0.000053
 000005.XSHE    0.000099
 000006.XSHE    0.000174
                  ...
 688368.XSHG    0.000065
 688369.XSHG    0.000064
 688388.XSHG    0.000157
 688389.XSHG    0.000036
 688399.XSHG    0.000070
 Name: weight, Length: 3767, dtype: float64,
 Timestamp('2020-02-05 00:00:00'): order_book_id
 000001.XSHE    0.006178
 000002.XSHE    0.007989
 000004.XSHE    0.000055
 000005.XSHE    0.000099
 000006.XSHE    0.000173
                  ...
 688368.XSHG    0.000065
 688369.XSHG    0.000072
 688388.XSHG    0.000165
 688389.XSHG    0.000042
 688399.XSHG    0.000069
 Name: weight, Length: 3767, dtype: float64,
 Timestamp('2020-02-06 00:00:00'): order_book_id
 000001.XSHE    0.006084
 000002.XSHE    0.007866
 000004.XSHE    0.000056
 000005.XSHE    0.000097
 000006.XSHE    0.000171
                  ...
 688368.XSHG    0.000066
 688369.XSHG    0.000073
 688388.XSHG    0.000166
 688389.XSHG    0.000044
 688399.XSHG    0.000062
 Name: weight, Length: 3768, dtype: float64,
 Timestamp('2020-02-07 00:00:00'): order_book_id
 000001.XSHE    0.005990
 000002.XSHE    0.007712
 000004.XSHE    0.000055
 000005.XSHE    0.000102
 000006.XSHE    0.000169
                  ...
 688368.XSHG    0.000072
 688369.XSHG    0.000072
 688388.XSHG    0.000168
 688389.XSHG    0.000041
 688399.XSHG    0.000059
 Name: weight, Length: 3769, dtype: float64,
 Timestamp('2020-02-10 00:00:00'): order_book_id
 000001.XSHE    0.005883
 000002.XSHE    0.007962
 000004.XSHE    0.000055
 000005.XSHE    0.000102
 000006.XSHE    0.000170
                  ...
 688368.XSHG    0.000070
 688369.XSHG    0.000066
 688388.XSHG    0.000177
 688389.XSHG    0.000037
 688399.XSHG    0.000055
 Name: weight, Length: 3770, dtype: float64,
 Timestamp('2020-02-11 00:00:00'): order_book_id
 000001.XSHE    0.005993
 000002.XSHE    0.008065
 000004.XSHE    0.000054
 000005.XSHE    0.000101
 000006.XSHE    0.000172
                  ...
 688368.XSHG    0.000065
 688369.XSHG    0.000061
 688388.XSHG    0.000168
 688389.XSHG    0.000038
 688399.XSHG    0.000054
 Name: weight, Length: 3771, dtype: float64,
 Timestamp('2020-02-12 00:00:00'): order_book_id
 000001.XSHE    0.005901
 000002.XSHE    0.007953
 000004.XSHE    0.000054
 000005.XSHE    0.000100
 000006.XSHE    0.000170
                  ...
 688368.XSHG    0.000069
 688369.XSHG    0.000062
 688388.XSHG    0.000169
 688389.XSHG    0.000038
 688399.XSHG    0.000054
 Name: weight, Length: 3772, dtype: float64,
 Timestamp('2020-02-13 00:00:00'): order_book_id
 000001.XSHE    0.005894
 000002.XSHE    0.008247
 000004.XSHE    0.000053
 000005.XSHE    0.000099
 000006.XSHE    0.000171
                  ...
 688368.XSHG    0.000069
 688369.XSHG    0.000061
 688388.XSHG    0.000166
 688389.XSHG    0.000039
 688399.XSHG    0.000056
 Name: weight, Length: 3775, dtype: float64,
 Timestamp('2020-02-14 00:00:00'): order_book_id
 000001.XSHE    0.005194
 000002.XSHE    0.008442
 000004.XSHE    0.000053
 000005.XSHE    0.000098
 000006.XSHE    0.000172
                  ...
 688368.XSHG    0.000066
 688369.XSHG    0.000060
 688388.XSHG    0.000160
 688389.XSHG    0.000036
 688399.XSHG    0.000052
 Name: weight, Length: 3775, dtype: float64,
 Timestamp('2020-02-17 00:00:00'): order_book_id
 000001.XSHE    0.005164
 000002.XSHE    0.008106
 000004.XSHE    0.000057
 000005.XSHE    0.000099
 000006.XSHE    0.000172
                  ...
 688368.XSHG    0.000069
 688369.XSHG    0.000060
 688388.XSHG    0.000169
 688389.XSHG    0.000035
 688399.XSHG    0.000051
 Name: weight, Length: 3776, dtype: float64,
 Timestamp('2020-02-18 00:00:00'): order_book_id
 000001.XSHE    0.005071
 000002.XSHE    0.007859
 000004.XSHE    0.000062
 000005.XSHE    0.000098
 000006.XSHE    0.000170
                  ...
 688368.XSHG    0.000073
 688369.XSHG    0.000061
 688388.XSHG    0.000173
 688389.XSHG    0.000035
 688399.XSHG    0.000052
 Name: weight, Length: 3778, dtype: float64,
 Timestamp('2020-02-19 00:00:00'): order_book_id
 000001.XSHE    0.005108
 000002.XSHE    0.007882
 000004.XSHE    0.000069
 000005.XSHE    0.000097
 000006.XSHE    0.000171
                  ...
 688368.XSHG    0.000069
 688369.XSHG    0.000058
 688388.XSHG    0.000169
 688389.XSHG    0.000033
 688399.XSHG    0.000049
 Name: weight, Length: 3779, dtype: float64,
 Timestamp('2020-02-20 00:00:00'): order_book_id
 000001.XSHE    0.005118
 000002.XSHE    0.007772
 000004.XSHE    0.000074
 000005.XSHE    0.000097
 000006.XSHE    0.000169
                  ...
 688368.XSHG    0.000066
 688369.XSHG    0.000054
 688388.XSHG    0.000166
 688389.XSHG    0.000033
 688399.XSHG    0.000046
 Name: weight, Length: 3780, dtype: float64,
 Timestamp('2020-02-21 00:00:00'): order_book_id
 000001.XSHE    0.005074
 000002.XSHE    0.007555
 000004.XSHE    0.000081
 000005.XSHE    0.000096
 000006.XSHE    0.000168
                  ...
 688368.XSHG    0.000064
 688369.XSHG    0.000054
 688388.XSHG    0.000162
 688389.XSHG    0.000033
 688399.XSHG    0.000046
 Name: weight, Length: 3781, dtype: float64,
 Timestamp('2020-02-24 00:00:00'): order_book_id
 000001.XSHE    0.004926
 000002.XSHE    0.007414
 000004.XSHE    0.000088
 000005.XSHE    0.000095
 000006.XSHE    0.000165
                  ...
 688369.XSHG    0.000055
 688388.XSHG    0.000159
 688389.XSHG    0.000035
 688398.XSHG    0.000049
 688399.XSHG    0.000047
 Name: weight, Length: 3783, dtype: float64,
 Timestamp('2020-02-25 00:00:00'): order_book_id
 000001.XSHE    0.004857
 000002.XSHE    0.007512
 000004.XSHE    0.000097
 000005.XSHE    0.000093
 000006.XSHE    0.000162
                  ...
 688369.XSHG    0.000055
 688388.XSHG    0.000163
 688389.XSHG    0.000036
 688398.XSHG    0.000050
 688399.XSHG    0.000049
 Name: weight, Length: 3785, dtype: float64,
 Timestamp('2020-02-26 00:00:00'): order_book_id
 000001.XSHE    0.004937
 000002.XSHE    0.007865
 000004.XSHE    0.000089
 000005.XSHE    0.000099
 000006.XSHE    0.000168
                  ...
 688369.XSHG    0.000054
 688388.XSHG    0.000151
 688389.XSHG    0.000032
 688398.XSHG    0.000050
 688399.XSHG    0.000048
 Name: weight, Length: 3787, dtype: float64,
 Timestamp('2020-02-27 00:00:00'): order_book_id
 000001.XSHE    0.004963
 000002.XSHE    0.007729
 000004.XSHE    0.000087
 000005.XSHE    0.000097
 000006.XSHE    0.000166
                  ...
 688369.XSHG    0.000058
 688388.XSHG    0.000151
 688389.XSHG    0.000032
 688398.XSHG    0.000047
 688399.XSHG    0.000047
 Name: weight, Length: 3787, dtype: float64,
 Timestamp('2020-02-28 00:00:00'): order_book_id
 000001.XSHE    0.004988
 000002.XSHE    0.008073
 000004.XSHE    0.000101
 000005.XSHE    0.000097
 000006.XSHE    0.000168
                  ...
 688369.XSHG    0.000057
 688388.XSHG    0.000142
 688389.XSHG    0.000033
 688398.XSHG    0.000045
 688399.XSHG    0.000054
 Name: weight, Length: 3788, dtype: float64,
 Timestamp('2020-03-02 00:00:00'): order_book_id
 000001.XSHE    0.004909
 000002.XSHE    0.008194
 000004.XSHE    0.000107
 000005.XSHE    0.000097
 000006.XSHE    0.000169
                  ...
 688369.XSHG    0.000057
 688388.XSHG    0.000142
 688389.XSHG    0.000033
 688398.XSHG    0.000045
 688399.XSHG    0.000051
 Name: weight, Length: 3790, dtype: float64,
 Timestamp('2020-03-03 00:00:00'): order_book_id
 000001.XSHE    0.004838
 000002.XSHE    0.008108
 000004.XSHE    0.000100
 000005.XSHE    0.000098
 000006.XSHE    0.000176
                  ...
 688369.XSHG    0.000058
 688388.XSHG    0.000142
 688389.XSHG    0.000032
 688398.XSHG    0.000044
 688399.XSHG    0.000050
 Name: weight, Length: 3790, dtype: float64,
 Timestamp('2020-03-04 00:00:00'): order_book_id
 000001.XSHE    0.004803
 000002.XSHE    0.008366
 000004.XSHE    0.000103
 000005.XSHE    0.000101
 000006.XSHE    0.000176
                  ...
 688369.XSHG    0.000058
 688388.XSHG    0.000141
 688389.XSHG    0.000031
 688398.XSHG    0.000045
 688399.XSHG    0.000049
 Name: weight, Length: 3790, dtype: float64,
 Timestamp('2020-03-05 00:00:00'): order_book_id
 000001.XSHE    0.004935
 000002.XSHE    0.008215
 000004.XSHE    0.000096
 000005.XSHE    0.000100
 000006.XSHE    0.000172
                  ...
 688369.XSHG    0.000055
 688388.XSHG    0.000141
 688389.XSHG    0.000030
 688398.XSHG    0.000044
 688399.XSHG    0.000047
 Name: weight, Length: 3793, dtype: float64,
 Timestamp('2020-03-06 00:00:00'): order_book_id
 000001.XSHE    0.004867
 000002.XSHE    0.007995
 000004.XSHE    0.000098
 000005.XSHE    0.000100
 000006.XSHE    0.000169
                  ...
 688369.XSHG    0.000053
 688388.XSHG    0.000146
 688389.XSHG    0.000031
 688398.XSHG    0.000045
 688399.XSHG    0.000048
 Name: weight, Length: 3794, dtype: float64,
 Timestamp('2020-03-09 00:00:00'): order_book_id
 000001.XSHE    0.004853
 000002.XSHE    0.008138
 000004.XSHE    0.000096
 000005.XSHE    0.000103
 000006.XSHE    0.000170
                  ...
 688369.XSHG    0.000051
 688388.XSHG    0.000137
 688389.XSHG    0.000032
 688398.XSHG    0.000044
 688399.XSHG    0.000045
 Name: weight, Length: 3794, dtype: float64,
 Timestamp('2020-03-10 00:00:00'): order_book_id
 000001.XSHE    0.004834
 000002.XSHE    0.008001
 000004.XSHE    0.000096
 000005.XSHE    0.000102
 000006.XSHE    0.000168
                  ...
 688369.XSHG    0.000052
 688388.XSHG    0.000144
 688389.XSHG    0.000030
 688398.XSHG    0.000043
 688399.XSHG    0.000043
 Name: weight, Length: 3796, dtype: float64,
 Timestamp('2020-03-11 00:00:00'): order_book_id
 000001.XSHE    0.004873
 000002.XSHE    0.007993
 000004.XSHE    0.000095
 000005.XSHE    0.000104
 000006.XSHE    0.000171
                  ...
 688388.XSHG    0.000144
 688389.XSHG    0.000030
 688396.XSHG    0.000409
 688398.XSHG    0.000043
 688399.XSHG    0.000044
 Name: weight, Length: 3797, dtype: float64,
 Timestamp('2020-03-12 00:00:00'): order_book_id
 000001.XSHE    0.004965
 000002.XSHE    0.008033
 000004.XSHE    0.000093
 000005.XSHE    0.000102
 000006.XSHE    0.000170
                  ...
 688388.XSHG    0.000141
 688389.XSHG    0.000030
 688396.XSHG    0.000415
 688398.XSHG    0.000043
 688399.XSHG    0.000048
 Name: weight, Length: 3797, dtype: float64,
 Timestamp('2020-03-13 00:00:00'): order_book_id
 000001.XSHE    0.004968
 000002.XSHE    0.007992
 000004.XSHE    0.000094
 000005.XSHE    0.000102
 000006.XSHE    0.000173
                  ...
 688388.XSHG    0.000140
 688389.XSHG    0.000029
 688396.XSHG    0.000428
 688398.XSHG    0.000041
 688399.XSHG    0.000047
 Name: weight, Length: 3798, dtype: float64,
 Timestamp('2020-03-16 00:00:00'): order_book_id
 000001.XSHE    0.004919
 000002.XSHE    0.008098
 000004.XSHE    0.000091
 000005.XSHE    0.000104
 000006.XSHE    0.000180
                  ...
 688388.XSHG    0.000139
 688389.XSHG    0.000029
 688396.XSHG    0.000429
 688398.XSHG    0.000041
 688399.XSHG    0.000048
 Name: weight, Length: 3798, dtype: float64,
 Timestamp('2020-03-17 00:00:00'): order_book_id
 000001.XSHE    0.004809
 000002.XSHE    0.007996
 000004.XSHE    0.000092
 000005.XSHE    0.000103
 000006.XSHE    0.000177
                  ...
 688388.XSHG    0.000137
 688389.XSHG    0.000029
 688396.XSHG    0.000445
 688398.XSHG    0.000040
 688399.XSHG    0.000045
 Name: weight, Length: 3798, dtype: float64,
 Timestamp('2020-03-18 00:00:00'): order_book_id
 000001.XSHE    0.004641
 000002.XSHE    0.007616
 000004.XSHE    0.000091
 000005.XSHE    0.000107
 000006.XSHE    0.000176
                  ...
 688388.XSHG    0.000140
 688389.XSHG    0.000029
 688396.XSHG    0.000438
 688398.XSHG    0.000039
 688399.XSHG    0.000045
 Name: weight, Length: 3798, dtype: float64,
 Timestamp('2020-03-19 00:00:00'): order_book_id
 000001.XSHE    0.004476
 000002.XSHE    0.007323
 000004.XSHE    0.000093
 000005.XSHE    0.000104
 000006.XSHE    0.000177
                  ...
 688388.XSHG    0.000140
 688389.XSHG    0.000029
 688396.XSHG    0.000447
 688398.XSHG    0.000039
 688399.XSHG    0.000044
 Name: weight, Length: 3799, dtype: float64,
 Timestamp('2020-03-20 00:00:00'): order_book_id
 000001.XSHE    0.004516
 000002.XSHE    0.007381
 000004.XSHE    0.000090
 000005.XSHE    0.000104
 000006.XSHE    0.000176
                  ...
 688388.XSHG    0.000135
 688389.XSHG    0.000029
 688396.XSHG    0.000429
 688398.XSHG    0.000040
 688399.XSHG    0.000046
 Name: weight, Length: 3799, dtype: float64,
 Timestamp('2020-03-23 00:00:00'): order_book_id
 000001.XSHE    0.004558
 000002.XSHE    0.007304
 000004.XSHE    0.000087
 000005.XSHE    0.000106
 000006.XSHE    0.000176
                  ...
 688388.XSHG    0.000121
 688389.XSHG    0.000031
 688396.XSHG    0.000389
 688398.XSHG    0.000041
 688399.XSHG    0.000047
 Name: weight, Length: 3800, dtype: float64,
 Timestamp('2020-03-24 00:00:00'): order_book_id
 000001.XSHE    0.004622
 000002.XSHE    0.007239
 000004.XSHE    0.000087
 000005.XSHE    0.000105
 000006.XSHE    0.000175
                  ...
 688388.XSHG    0.000120
 688389.XSHG    0.000031
 688396.XSHG    0.000384
 688398.XSHG    0.000041
 688399.XSHG    0.000046
 Name: weight, Length: 3800, dtype: float64,
 Timestamp('2020-03-25 00:00:00'): order_book_id
 000001.XSHE    0.004596
 000002.XSHE    0.007506
 000004.XSHE    0.000086
 000005.XSHE    0.000104
 000006.XSHE    0.000175
                  ...
 688388.XSHG    0.000122
 688389.XSHG    0.000031
 688396.XSHG    0.000377
 688398.XSHG    0.000041
 688399.XSHG    0.000047
 Name: weight, Length: 3802, dtype: float64,
 Timestamp('2020-03-26 00:00:00'): order_book_id
 000001.XSHE    0.004696
 000002.XSHE    0.007472
 000004.XSHE    0.000085
 000005.XSHE    0.000104
 000006.XSHE    0.000173
                  ...
 688388.XSHG    0.000119

In [24]:
last_two_df = dict(list(all_df.items())[-2:])
last_two_df

{Timestamp('2026-06-04 00:00:00'): order_book_id
 000001.XSHE    0.001671
 000002.XSHE    0.000393
 000004.XSHE    0.000005
 000006.XSHE    0.000135
 000007.XSHE    0.000054
                  ...
 688818.XSHG    0.000172
 688819.XSHG    0.000060
 688820.XSHG    0.000626
 688981.XSHG    0.004808
 689009.XSHG    0.000035
 Name: weight, Length: 5206, dtype: float64,
 Timestamp('2026-06-05 00:00:00'): order_book_id
 000001.XSHE    0.001715
 000002.XSHE    0.000403
 000004.XSHE    0.000005
 000006.XSHE    0.000139
 000007.XSHE    0.000054
                  ...
 688818.XSHG    0.000185
 688819.XSHG    0.000061
 688820.XSHG    0.000573
 688981.XSHG    0.004593
 689009.XSHG    0.000036
 Name: weight, Length: 5206, dtype: float64}

In [25]:
pd.to_pickle(last_two_df, os.path.join(r"E:\SJTU\intern\gtht\barra\data_base\index_component_日频", "866011.RI_20_26D_dict_last_two.pkl"))

In [1]:
#检查结果
import pandas as pd
srcdir = "E:/SJTU/intern/gtht/barra/data_base/basis/output"

df = pd.read_pickle(f"{srcdir}/IM2609_dividend.pkl")
df

          date  dividend_point
0   2026-01-19        0.000000
1   2026-01-20        0.000000
2   2026-01-21        0.000000
3   2026-01-22        0.000000
4   2026-01-23        0.000000
..         ...             ...
118 2026-07-17        5.095158
119 2026-07-20        4.677067
120 2026-07-21        4.043231
121 2026-07-22        3.505639
122 2026-07-23        2.426333

[123 rows x 2 columns]

In [2]:
df2 = pd.read_pickle(f"{srcdir}/IM2612_dividend.pkl")
df2

         date  dividend_point
0  2026-04-20        3.367715
1  2026-04-21        5.520045
2  2026-04-22        7.977589
3  2026-04-23       11.326055
4  2026-04-24       16.002223
..        ...             ...
60 2026-07-17        5.095158
61 2026-07-20        4.677067
62 2026-07-21        4.043231
63 2026-07-22        3.505639
64 2026-07-23        2.426333

[65 rows x 2 columns]

提取全A个股收益率信息

In [ ]:
#首先更新全A成分股信息
srcdir = "E:/SJTU/intern/gtht/barra/data_base/index_component_日频"
import pandas as pd

df = pd.read_pickle(f"{srcdir}/866011.RI_19_26D_dict.pkl")

temp = rqdatac.index_weights("866011.RI", start_date="2019-01-01", end_date="2020-01-01", market='cn')
trade_dates = temp.index.get_level_values(0).unique()
for dt in trade_dates:
    df[dt] = temp.loc[dt]["weight"]
    print(dt)

import pickle
# 使用内置的 pickle 模块写入文件
with open(f"{srcdir}/866011.RI_19_26D_dict.pkl", "wb") as f:
    pickle.dump(df, f)

2019-01-02 00:00:00
2019-01-03 00:00:00
2019-01-04 00:00:00
2019-01-07 00:00:00
2019-01-08 00:00:00
2019-01-09 00:00:00
2019-01-10 00:00:00
2019-01-11 00:00:00
2019-01-14 00:00:00
2019-01-15 00:00:00
2019-01-16 00:00:00
2019-01-17 00:00:00
2019-01-18 00:00:00
2019-01-21 00:00:00
2019-01-22 00:00:00
2019-01-23 00:00:00
2019-01-24 00:00:00
2019-01-25 00:00:00
2019-01-28 00:00:00
2019-01-29 00:00:00
2019-01-30 00:00:00
2019-01-31 00:00:00
2019-02-01 00:00:00
2019-02-11 00:00:00
2019-02-12 00:00:00
2019-02-13 00:00:00
2019-02-14 00:00:00
2019-02-15 00:00:00
2019-02-18 00:00:00
2019-02-19 00:00:00
2019-02-20 00:00:00
2019-02-21 00:00:00
2019-02-22 00:00:00
2019-02-25 00:00:00
2019-02-26 00:00:00
2019-02-27 00:00:00
2019-02-28 00:00:00
2019-03-01 00:00:00
2019-03-04 00:00:00
2019-03-05 00:00:00
2019-03-06 00:00:00
2019-03-07 00:00:00
2019-03-08 00:00:00
2019-03-11 00:00:00
2019-03-12 00:00:00
2019-03-13 00:00:00
2019-03-14 00:00:00
2019-03-15 00:00:00
2019-03-18 00:00:00
2019-03-19 00:00:00
2019-03-20 00:00:00
2019-03-21 00:00:00
2019-03-22 00:00:00
2019-03-25 00:00:00
2019-03-26 00:00:00
2019-03-27 00:00:00
2019-03-28 00:00:00
2019-03-29 00:00:00
2019-04-01 00:00:00
2019-04-02 00:00:00
2019-04-03 00:00:00
2019-04-04 00:00:00
2019-04-08 00:00:00
2019-04-09 00:00:00
2019-04-10 00:00:00
2019-04-11 00:00:00
2019-04-12 00:00:00
2019-04-15 00:00:00
2019-04-16 00:00:00
2019-04-17 00:00:00
2019-04-18 00:00:00
2019-04-19 00:00:00
2019-04-22 00:00:00
2019-04-23 00:00:00
2019-04-24 00:00:00
2019-04-25 00:00:00
2019-04-26 00:00:00
2019-04-29 00:00:00
2019-04-30 00:00:00
2019-05-06 00:00:00
2019-05-07 00:00:00
2019-05-08 00:00:00
2019-05-09 00:00:00
2019-05-10 00:00:00
2019-05-13 00:00:00
2019-05-14 00:00:00
2019-05-15 00:00:00
2019-05-16 00:00:00
2019-05-17 00:00:00
2019-05-20 00:00:00
2019-05-21 00:00:00
2019-05-22 00:00:00
2019-05-23 00:00:00
2019-05-24 00:00:00
2019-05-27 00:00:00
2019-05-28 00:00:00
2019-05-29 00:00:00
2019-05-30 00:00:00
2019-05-31 00:00:00
2019-06-03 00:00:00
2019-06-04 00:00:00
2019-06-05 00:00:00
2019-06-06 00:00:00
2019-06-10 00:00:00
2019-06-11 00:00:00
2019-06-12 00:00:00
2019-06-13 00:00:00
2019-06-14 00:00:00
2019-06-17 00:00:00
2019-06-18 00:00:00
2019-06-19 00:00:00
2019-06-20 00:00:00
2019-06-21 00:00:00
2019-06-24 00:00:00
2019-06-25 00:00:00
2019-06-26 00:00:00
2019-06-27 00:00:00
2019-06-28 00:00:00
2019-07-01 00:00:00
2019-07-02 00:00:00
2019-07-03 00:00:00
2019-07-04 00:00:00
2019-07-05 00:00:00
2019-07-08 00:00:00
2019-07-09 00:00:00
2019-07-10 00:00:00
2019-07-11 00:00:00
2019-07-12 00:00:00
2019-07-15 00:00:00
2019-07-16 00:00:00
2019-07-17 00:00:00
2019-07-18 00:00:00
2019-07-19 00:00:00
2019-07-22 00:00:00
2019-07-23 00:00:00
2019-07-24 00:00:00
2019-07-25 00:00:00
2019-07-26 00:00:00
2019-07-29 00:00:00
2019-07-30 00:00:00
2019-07-31 00:00:00
2019-08-01 00:00:00
2019-08-02 00:00:00
2019-08-05 00:00:00
2019-08-06 00:00:00
2019-08-07 00:00:00
2019-08-08 00:00:00
2019-08-09 00:00:00
2019-08-12 00:00:00
2019-08-13 00:00:00
2019-08-14 00:00:00
2019-08-15 00:00:00
2019-08-16 00:00:00
2019-08-19 00:00:00
2019-08-20 00:00:00
2019-08-21 00:00:00
2019-08-22 00:00:00
2019-08-23 00:00:00
2019-08-26 00:00:00
2019-08-27 00:00:00
2019-08-28 00:00:00
2019-08-29 00:00:00
2019-08-30 00:00:00
2019-09-02 00:00:00
2019-09-03 00:00:00
2019-09-04 00:00:00
2019-09-05 00:00:00
2019-09-06 00:00:00
2019-09-09 00:00:00
2019-09-10 00:00:00
2019-09-11 00:00:00
2019-09-12 00:00:00
2019-09-16 00:00:00
2019-09-17 00:00:00
2019-09-18 00:00:00
2019-09-19 00:00:00
2019-09-20 00:00:00
2019-09-23 00:00:00
2019-09-24 00:00:00
2019-09-25 00:00:00
2019-09-26 00:00:00
2019-09-27 00:00:00
2019-09-30 00:00:00
2019-10-08 00:00:00
2019-10-09 00:00:00
2019-10-10 00:00:00
2019-10-11 00:00:00
2019-10-14 00:00:00
2019-10-15 00:00:00
2019-10-16 00:00:00
2019-10-17 00:00:00
2019-10-18 00:00:00
2019-10-21 00:00:00
2019-10-22 00:00:00
2019-10-23 00:00:00
2019-10-24 00:00:00
2019-10-25 00:00:00
2019-10-28 00:00:00
2019-10-29 00:00:00
2019-10-30 00:00:00
2019-10-31 00:00:00
2019-11-01 00:00:00
2019-11-04 00:00:00
2019-11-05 00:00:00
2019-11-06 00:00:00
2019-11-07 00:00:00
2019-11-08 00:00:00
2019-11-11 00:00:00
2019-11-12 00:00:00
2019-11-13 00:00:00
2019-11-14 00:00:00
2019-11-15 00:00:00
2019-11-18 00:00:00
2019-11-19 00:00:00
2019-11-20 00:00:00
2019-11-21 00:00:00
2019-11-22 00:00:00
2019-11-25 00:00:00
2019-11-26 00:00:00
2019-11-27 00:00:00
2019-11-28 00:00:00
2019-11-29 00:00:00
2019-12-02 00:00:00
2019-12-03 00:00:00
2019-12-04 00:00:00
2019-12-05 00:00:00
2019-12-06 00:00:00
2019-12-09 00:00:00
2019-12-10 00:00:00
2019-12-11 00:00:00
2019-12-12 00:00:00
2019-12-13 00:00:00
2019-12-16 00:00:00
2019-12-17 00:00:00
2019-12-18 00:00:00
2019-12-19 00:00:00
2019-12-20 00:00:00
2019-12-23 00:00:00
2019-12-24 00:00:00
2019-12-25 00:00:00
2019-12-26 00:00:00
2019-12-27 00:00:00
2019-12-30 00:00:00
2019-12-31 00:00:00

In [33]:
#其次，提取个股每日收益率
stkdir = "E:/SJTU/intern/gtht/barra/data_base/stk_ret"
df = pd.read_pickle(f"{srcdir}/866011.RI_19_26D_dict.pkl")
res = pd.read_pickle(f"{stkdir}/全A_ret_20_26D_dict.pkl")

for dt in list(df.keys()):
    if dt in list(res.keys()):
        continue
    stk = df[dt].index.tolist()
    stk_fb = [s for s in stk if not s.endswith(".BJSE")]
    df_ret = get_price_change_rate(stk_fb, start_date=dt, end_date=dt, expect_df=True, market='cn')
    res[dt] = df_ret.T[dt]
    res[dt].name = "ret"
    print(dt)
    
with open(f"{stkdir}/全A_ret_20_26D_dict.pkl", "wb") as f:
    pickle.dump(res, f)
res

2019-01-02 00:00:00
2019-01-03 00:00:00
2019-01-04 00:00:00
2019-01-07 00:00:00
2019-01-08 00:00:00
2019-01-09 00:00:00
2019-01-10 00:00:00
2019-01-11 00:00:00
2019-01-14 00:00:00
2019-01-15 00:00:00
2019-01-16 00:00:00
2019-01-17 00:00:00
2019-01-18 00:00:00
2019-01-21 00:00:00
2019-01-22 00:00:00
2019-01-23 00:00:00
2019-01-24 00:00:00
2019-01-25 00:00:00
2019-01-28 00:00:00
2019-01-29 00:00:00
2019-01-30 00:00:00
2019-01-31 00:00:00
2019-02-01 00:00:00
2019-02-11 00:00:00
2019-02-12 00:00:00
2019-02-13 00:00:00
2019-02-14 00:00:00
2019-02-15 00:00:00
2019-02-18 00:00:00
2019-02-19 00:00:00
2019-02-20 00:00:00
2019-02-21 00:00:00
2019-02-22 00:00:00
2019-02-25 00:00:00
2019-02-26 00:00:00
2019-02-27 00:00:00
2019-02-28 00:00:00
2019-03-01 00:00:00
2019-03-04 00:00:00
2019-03-05 00:00:00
2019-03-06 00:00:00
2019-03-07 00:00:00
2019-03-08 00:00:00
2019-03-11 00:00:00
2019-03-12 00:00:00
2019-03-13 00:00:00
2019-03-14 00:00:00
2019-03-15 00:00:00
2019-03-18 00:00:00
2019-03-19 00:00:00
2019-03-20 00:00:00
2019-03-21 00:00:00
2019-03-22 00:00:00
2019-03-25 00:00:00
2019-03-26 00:00:00
2019-03-27 00:00:00
2019-03-28 00:00:00
2019-03-29 00:00:00
2019-04-01 00:00:00
2019-04-02 00:00:00
2019-04-03 00:00:00
2019-04-04 00:00:00
2019-04-08 00:00:00
2019-04-09 00:00:00
2019-04-10 00:00:00
2019-04-11 00:00:00
2019-04-12 00:00:00
2019-04-15 00:00:00
2019-04-16 00:00:00
2019-04-17 00:00:00
2019-04-18 00:00:00
2019-04-19 00:00:00
2019-04-22 00:00:00
2019-04-23 00:00:00
2019-04-24 00:00:00
2019-04-25 00:00:00
2019-04-26 00:00:00
2019-04-29 00:00:00
2019-04-30 00:00:00
2019-05-06 00:00:00
2019-05-07 00:00:00
2019-05-08 00:00:00
2019-05-09 00:00:00
2019-05-10 00:00:00
2019-05-13 00:00:00
2019-05-14 00:00:00
2019-05-15 00:00:00
2019-05-16 00:00:00
2019-05-17 00:00:00
2019-05-20 00:00:00
2019-05-21 00:00:00
2019-05-22 00:00:00
2019-05-23 00:00:00
2019-05-24 00:00:00
2019-05-27 00:00:00
2019-05-28 00:00:00
2019-05-29 00:00:00
2019-05-30 00:00:00
2019-05-31 00:00:00
2019-06-03 00:00:00
2019-06-04 00:00:00
2019-06-05 00:00:00
2019-06-06 00:00:00
2019-06-10 00:00:00
2019-06-11 00:00:00
2019-06-12 00:00:00
2019-06-13 00:00:00
2019-06-14 00:00:00
2019-06-17 00:00:00
2019-06-18 00:00:00
2019-06-19 00:00:00
2019-06-20 00:00:00
2019-06-21 00:00:00
2019-06-24 00:00:00
2019-06-25 00:00:00
2019-06-26 00:00:00
2019-06-27 00:00:00
2019-06-28 00:00:00
2019-07-01 00:00:00
2019-07-02 00:00:00
2019-07-03 00:00:00
2019-07-04 00:00:00
2019-07-05 00:00:00
2019-07-08 00:00:00
2019-07-09 00:00:00
2019-07-10 00:00:00
2019-07-11 00:00:00
2019-07-12 00:00:00
2019-07-15 00:00:00
2019-07-16 00:00:00
2019-07-17 00:00:00
2019-07-18 00:00:00
2019-07-19 00:00:00
2019-07-22 00:00:00
2019-07-23 00:00:00
2019-07-24 00:00:00
2019-07-25 00:00:00
2019-07-26 00:00:00
2019-07-29 00:00:00
2019-07-30 00:00:00
2019-07-31 00:00:00
2019-08-01 00:00:00
2019-08-02 00:00:00
2019-08-05 00:00:00
2019-08-06 00:00:00
2019-08-07 00:00:00
2019-08-08 00:00:00
2019-08-09 00:00:00
2019-08-12 00:00:00
2019-08-13 00:00:00
2019-08-14 00:00:00
2019-08-15 00:00:00
2019-08-16 00:00:00
2019-08-19 00:00:00
2019-08-20 00:00:00
2019-08-21 00:00:00
2019-08-22 00:00:00
2019-08-23 00:00:00
2019-08-26 00:00:00
2019-08-27 00:00:00
2019-08-28 00:00:00
2019-08-29 00:00:00
2019-08-30 00:00:00
2019-09-02 00:00:00
2019-09-03 00:00:00
2019-09-04 00:00:00
2019-09-05 00:00:00
2019-09-06 00:00:00
2019-09-09 00:00:00
2019-09-10 00:00:00
2019-09-11 00:00:00
2019-09-12 00:00:00
2019-09-16 00:00:00
2019-09-17 00:00:00
2019-09-18 00:00:00
2019-09-19 00:00:00
2019-09-20 00:00:00
2019-09-23 00:00:00
2019-09-24 00:00:00
2019-09-25 00:00:00
2019-09-26 00:00:00
2019-09-27 00:00:00
2019-09-30 00:00:00
2019-10-08 00:00:00
2019-10-09 00:00:00
2019-10-10 00:00:00
2019-10-11 00:00:00
2019-10-14 00:00:00
2019-10-15 00:00:00
2019-10-16 00:00:00
2019-10-17 00:00:00
2019-10-18 00:00:00
2019-10-21 00:00:00
2019-10-22 00:00:00
2019-10-23 00:00:00
2019-10-24 00:00:00
2019-10-25 00:00:00
2019-10-28 00:00:00
2019-10-29 00:00:00
2019-10-30 00:00:00
2019-10-31 00:00:00
2019-11-01 00:00:00
2019-11-04 00:00:00
2019-11-05 00:00:00
2019-11-06 00:00:00
2019-11-07 00:00:00
2019-11-08 00:00:00
2019-11-11 00:00:00
2019-11-12 00:00:00
2019-11-13 00:00:00
2019-11-14 00:00:00
2019-11-15 00:00:00
2019-11-18 00:00:00
2019-11-19 00:00:00
2019-11-20 00:00:00
2019-11-21 00:00:00
2019-11-22 00:00:00
2019-11-25 00:00:00
2019-11-26 00:00:00
2019-11-27 00:00:00
2019-11-28 00:00:00
2019-11-29 00:00:00
2019-12-02 00:00:00
2019-12-03 00:00:00
2019-12-04 00:00:00
2019-12-05 00:00:00
2019-12-06 00:00:00
2019-12-09 00:00:00
2019-12-10 00:00:00
2019-12-11 00:00:00
2019-12-12 00:00:00
2019-12-13 00:00:00
2019-12-16 00:00:00
2019-12-17 00:00:00
2019-12-18 00:00:00
2019-12-19 00:00:00
2019-12-20 00:00:00
2019-12-23 00:00:00
2019-12-24 00:00:00
2019-12-25 00:00:00
2019-12-26 00:00:00
2019-12-27 00:00:00
2019-12-30 00:00:00
2019-12-31 00:00:00

{Timestamp('2020-01-02 00:00:00'): order_book_id
 000001.XSHE    0.025532
 000002.XSHE    0.011809
 000004.XSHE   -0.011510
 000005.XSHE    0.016181
 000006.XSHE    0.007463
                  ...
 688368.XSHG   -0.016727
 688369.XSHG    0.020252
 688388.XSHG    0.012882
 688389.XSHG    0.024970
 688399.XSHG   -0.000345
 Name: ret, Length: 3753, dtype: float64,
 Timestamp('2020-01-03 00:00:00'): order_book_id
 000001.XSHE    0.018376
 000002.XSHE   -0.015663
 000004.XSHE    0.000896
 000005.XSHE    0.003185
 000006.XSHE    0.014815
                  ...
 688368.XSHG   -0.019425
 688369.XSHG    0.018682
 688388.XSHG   -0.027875
 688389.XSHG    0.008913
 688399.XSHG    0.005529
 Name: ret, Length: 3754, dtype: float64,
 Timestamp('2020-01-06 00:00:00'): order_book_id
 000001.XSHE   -0.006403
 000002.XSHE   -0.016849
 000004.XSHE   -0.026846
 000005.XSHE    0.000000
 000006.XSHE   -0.003650
                  ...
 688368.XSHG    0.022154
 688369.XSHG   -0.015392
 688388.XSHG    0.066308
 688389.XSHG   -0.002945
 688399.XSHG    0.008247
 Name: ret, Length: 3755, dtype: float64,
 Timestamp('2020-01-07 00:00:00'): order_book_id
 000001.XSHE    0.004687
 000002.XSHE    0.007934
 000004.XSHE    0.016092
 000005.XSHE    0.015873
 000006.XSHE    0.005495
                  ...
 688368.XSHG    0.008028
 688369.XSHG    0.051389
 688388.XSHG   -0.010924
 688389.XSHG    0.026580
 688399.XSHG    0.013292
 Name: ret, Length: 3755, dtype: float64,
 Timestamp('2020-01-08 00:00:00'): order_book_id
 000001.XSHE   -0.028571
 000002.XSHE   -0.002519
 000004.XSHE   -0.014480
 000005.XSHE   -0.015625
 000006.XSHE   -0.018215
                  ...
 688368.XSHG    0.001138
 688369.XSHG   -0.016925
 688388.XSHG    0.004248
 688389.XSHG   -0.009206
 688399.XSHG   -0.007568
 Name: ret, Length: 3755, dtype: float64,
 Timestamp('2020-01-09 00:00:00'): order_book_id
 000001.XSHE    0.007803
 000002.XSHE    0.016414
 000004.XSHE    0.024793
 000005.XSHE    0.019048
 000006.XSHE    0.014842
                  ...
 688368.XSHG    0.032500
 688369.XSHG    0.039260
 688388.XSHG    0.004907
 688389.XSHG    0.010453
 688399.XSHG    0.024911
 Name: ret, Length: 3756, dtype: float64,
 Timestamp('2020-01-10 00:00:00'): order_book_id
 000001.XSHE   -0.005956
 000002.XSHE   -0.022981
 000004.XSHE    0.000448
 000005.XSHE   -0.012461
 000006.XSHE   -0.001828
                  ...
 688368.XSHG   -0.009465
 688369.XSHG   -0.003871
 688388.XSHG   -0.025088
 688389.XSHG    0.020115
 688399.XSHG    0.010913
 Name: ret, Length: 3757, dtype: float64,
 Timestamp('2020-01-13 00:00:00'): order_book_id
 000001.XSHE    0.017975
 000002.XSHE    0.006993
 000004.XSHE    0.031348
 000005.XSHE   -0.003155
 000006.XSHE    0.012821
                  ...
 688368.XSHG    0.006667
 688369.XSHG    0.005906
 688388.XSHG    0.031088
 688389.XSHG    0.032113
 688399.XSHG   -0.002617
 Name: ret, Length: 3759, dtype: float64,
 Timestamp('2020-01-14 00:00:00'): order_book_id
 000001.XSHE   -0.013537
 000002.XSHE   -0.009154
 000004.XSHE   -0.001303
 000005.XSHE    0.012658
 000006.XSHE   -0.005425
                  ...
 688368.XSHG    0.000000
 688369.XSHG   -0.002009
 688388.XSHG    0.044054
 688389.XSHG   -0.001092
 688399.XSHG    0.034765
 Name: ret, Length: 3760, dtype: float64,
 Timestamp('2020-01-15 00:00:00'): order_book_id
 000001.XSHE   -0.014320
 000002.XSHE   -0.028672
 000004.XSHE   -0.019565
 000005.XSHE   -0.009375
 000006.XSHE   -0.005455
                  ...
 688368.XSHG   -0.022627
 688369.XSHG   -0.009135
 688388.XSHG   -0.026151
 688389.XSHG   -0.016940
 688399.XSHG   -0.004120
 Name: ret, Length: 3760, dtype: float64,
 Timestamp('2020-01-16 00:00:00'): order_book_id
 000001.XSHE   -0.011501
 000002.XSHE    0.001312
 000004.XSHE   -0.003991
 000005.XSHE   -0.012618
 000006.XSHE   -0.014625
                  ...
 688368.XSHG    0.042801
 688369.XSHG    0.026719
 688388.XSHG    0.003624
 688389.XSHG    0.010561
 688399.XSHG    0.009707
 Name: ret, Length: 3760, dtype: float64,
 Timestamp('2020-01-17 00:00:00'): order_book_id
 000001.XSHE    0.003674
 000002.XSHE   -0.002293
 000004.XSHE   -0.009795
 000005.XSHE    0.000000
 000006.XSHE   -0.007421
                  ...
 688368.XSHG    0.064977
 688369.XSHG    0.051286
 688388.XSHG    0.034143
 688389.XSHG    0.049505
 688399.XSHG    0.032309
 Name: ret, Length: 3763, dtype: float64,
 Timestamp('2020-01-20 00:00:00'): order_book_id
 000001.XSHE    0.003661
 000002.XSHE   -0.019370
 000004.XSHE    0.049011
 000005.XSHE    0.003195
 000006.XSHE    0.003738
                  ...
 688368.XSHG    0.200020
 688369.XSHG    0.010133
 688388.XSHG   -0.021746
 688389.XSHG    0.055556
 688399.XSHG    0.200000
 Name: ret, Length: 3763, dtype: float64,
 Timestamp('2020-01-21 00:00:00'): order_book_id
 000001.XSHE   -0.027356
 000002.XSHE   -0.022096
 000004.XSHE    0.009430
 000005.XSHE   -0.031847
 000006.XSHE   -0.024209
                  ...
 688368.XSHG   -0.120329
 688369.XSHG   -0.035540
 688388.XSHG   -0.068798
 688389.XSHG   -0.001986
 688399.XSHG    0.195929
 Name: ret, Length: 3763, dtype: float64,
 Timestamp('2020-01-22 00:00:00'): order_book_id
 000001.XSHE    0.005625
 000002.XSHE    0.030811
 000004.XSHE    0.006369
 000005.XSHE    0.003289
 000006.XSHE    0.003817
                  ...
 688368.XSHG    0.127059
 688369.XSHG    0.013373
 688388.XSHG    0.041645
 688389.XSHG   -0.032836
 688399.XSHG   -0.053191
 Name: ret, Length: 3764, dtype: float64,
 Timestamp('2020-01-23 00:00:00'): order_book_id
 000001.XSHE   -0.034183
 000002.XSHE   -0.037529
 000004.XSHE   -0.037131
 000005.XSHE   -0.026230
 000006.XSHE   -0.034221
                  ...
 688368.XSHG   -0.008291
 688369.XSHG   -0.061584
 688388.XSHG   -0.013717
 688389.XSHG   -0.040638
 688399.XSHG    0.100000
 Name: ret, Length: 3764, dtype: float64,
 Timestamp('2020-02-03 00:00:00'): order_book_id
 000001.XSHE   -0.099743
 000002.XSHE   -0.081090
 000004.XSHE   -0.099912
 000005.XSHE   -0.101010
 000006.XSHE   -0.100394
                  ...
 688368.XSHG   -0.200034
 688369.XSHG    0.036094
 688388.XSHG   -0.096676
 688389.XSHG    0.200000
 688399.XSHG    0.200000
 Name: ret, Length: 3765, dtype: float64,
 Timestamp('2020-02-04 00:00:00'): order_book_id
 000001.XSHE    0.043603
 000002.XSHE    0.037176
 000004.XSHE   -0.039435
 000005.XSHE   -0.018727
 000006.XSHE   -0.028446
                  ...
 688368.XSHG    0.084895
 688369.XSHG    0.199970
 688388.XSHG    0.163537
 688389.XSHG    0.005809
 688399.XSHG   -0.020174
 Name: ret, Length: 3767, dtype: float64,
 Timestamp('2020-02-05 00:00:00'): order_book_id
 000001.XSHE    0.002055
 000002.XSHE    0.000724
 000004.XSHE    0.070451
 000005.XSHE    0.022901
 000006.XSHE    0.013514
                  ...
 688368.XSHG    0.025521
 688369.XSHG    0.141762
 688388.XSHG    0.072777
 688389.XSHG    0.199023
 688399.XSHG    0.012944
 Name: ret, Length: 3767, dtype: float64,
 Timestamp('2020-02-06 00:00:00'): order_book_id
 000001.XSHE    0.009569
 000002.XSHE    0.009407
 000004.XSHE    0.030303
 000005.XSHE    0.011194
 000006.XSHE    0.013333
                  ...
 688368.XSHG    0.045318
 688369.XSHG    0.040286
 688388.XSHG    0.031438
 688389.XSHG    0.070026
 688399.XSHG   -0.078731
 Name: ret, Length: 3768, dtype: float64,
 Timestamp('2020-02-07 00:00:00'): order_book_id
 000001.XSHE   -0.010156
 000002.XSHE   -0.014337
 000004.XSHE   -0.008732
 000005.XSHE    0.047970
 000006.XSHE   -0.008772
                  ...
 688368.XSHG    0.090134
 688369.XSHG    0.000000
 688388.XSHG    0.017355
 688389.XSHG   -0.052632
 688399.XSHG   -0.056600
 Name: ret, Length: 3769, dtype: float64,
 Timestamp('2020-02-10 00:00:00'): order_book_id
 000001.XSHE   -0.008208
 000002.XSHE    0.042545
 000004.XSHE    0.015299
 000005.XSHE    0.010563
 000006.XSHE    0.015487
                  ...
 688368.XSHG   -0.014276
 688369.XSHG   -0.082531
 688388.XSHG    0.063647
 688389.XSHG   -0.081871
 688399.XSHG   -0.057825
 Name: ret, Length: 3770, dtype: float64,
 Timestamp('2020-02-11 00:00:00'): order_book_id
 000001.XSHE    0.020000
 000002.XSHE    0.014301
 000004.XSHE   -0.024201
 000005.XSHE   -0.006969
 000006.XSHE    0.015251
                  ...
 688368.XSHG   -0.077500
 688369.XSHG   -0.073925
 688388.XSHG   -0.050270
 688389.XSHG    0.002787
 688399.XSHG   -0.014453
 Name: ret, Length: 3771, dtype: float64,
 Timestamp('2020-02-12 00:00:00'): order_book_id
 000001.XSHE   -0.001352
 000002.XSHE    0.000000
 000004.XSHE    0.012167
 000005.XSHE    0.007018
 000006.XSHE    0.002146
                  ...
 688368.XSHG    0.086814
 688369.XSHG    0.038605
 688388.XSHG    0.019867
 688389.XSHG    0.015482
 688399.XSHG    0.008927
 Name: ret, Length: 3772, dtype: float64,
 Timestamp('2020-02-13 00:00:00'): order_book_id
 000001.XSHE   -0.008125
 000002.XSHE    0.029917
 000004.XSHE   -0.015257
 000005.XSHE   -0.020906
 000006.XSHE   -0.002141
                  ...
 688368.XSHG   -0.011006
 688369.XSHG   -0.020624
 688388.XSHG   -0.027689
 688389.XSHG    0.022283
 688399.XSHG    0.046977
 Name: ret, Length: 3775, dtype: float64,
 Timestamp('2020-02-14 00:00:00'): order_book_id
 000001.XSHE    0.025939
 000002.XSHE    0.028381
 000004.XSHE    0.001878
 000005.XSHE   -0.003559
 000006.XSHE    0.012876
                  ...
 688368.XSHG   -0.034950
 688369.XSHG   -0.014324
 688388.XSHG   -0.031483
 688389.XSHG   -0.069981
 688399.XSHG   -0.075453
 Name: ret, Length: 3775, dtype: float64,
 Timestamp('2020-02-17 00:00:00'): order_book_id
 000001.XSHE    0.022621
 000002.XSHE   -0.012338
 000004.XSHE    0.099813
 000005.XSHE    0.035714
 000006.XSHE    0.025424
                  ...
 688368.XSHG    0.067568
 688369.XSHG    0.019749
 688388.XSHG    0.087914
 688389.XSHG    0.016447
 688399.XSHG    0.006529
 Name: ret, Length: 3776, dtype: float64,
 Timestamp('2020-02-18 00:00:00'): order_book_id
 000001.XSHE   -0.011061
 000002.XSHE   -0.023669
 000004.XSHE    0.100128
 000005.XSHE    0.000000
 000006.XSHE   -0.006198
                  ...
 688368.XSHG    0.064979
 688369.XSHG    0.032521
 688388.XSHG    0.032188
 688389.XSHG   -0.004045
 688399.XSHG    0.030919
 Name: ret, Length: 3778, dtype: float64,
 Timestamp('2020-02-19 00:00:00'): order_book_id
 000001.XSHE    0.002632
 000002.XSHE   -0.001684
 000004.XSHE    0.099923
 000005.XSHE   -0.010345
 000006.XSHE    0.006237
                  ...
 688368.XSHG   -0.051743
 688369.XSHG   -0.058629
 688388.XSHG   -0.027632
 688389.XSHG   -0.052803
 688399.XSHG   -0.058305
 Name: ret, Length: 3779, dtype: float64,
 Timestamp('2020-02-20 00:00:00'): order_book_id
 000001.XSHE    0.022966
 000002.XSHE    0.006745
 000004.XSHE    0.100000
 000005.XSHE    0.013937
 000006.XSHE    0.008264
                  ...
 688368.XSHG   -0.019888
 688369.XSHG   -0.054261
 688388.XSHG    0.000000
 688389.XSHG    0.013722
 688399.XSHG   -0.042316
 Name: ret, Length: 3780, dtype: float64,
 Timestamp('2020-02-21 00:00:00'): order_book_id
 000001.XSHE   -0.000641
 000002.XSHE   -0.020101
 000004.XSHE    0.099872
 000005.XSHE    0.003436
 000006.XSHE    0.002049
                  ...
 688368.XSHG   -0.023105
 688369.XSHG    0.018948
 688388.XSHG   -0.014208
 688389.XSHG    0.016497
 688399.XSHG   -0.004186
 Name: ret, Length: 3781, dtype: float64,
 Timestamp('2020-02-24 00:00:00'): order_book_id
 000001.XSHE   -0.022465
 000002.XSHE   -0.011966
 000004.XSHE    0.100116
 000005.XSHE   -0.006849
 000006.XSHE   -0.014315
                  ...
 688369.XSHG    0.012614
 688388.XSHG   -0.010295
 688389.XSHG    0.048689
 688398.XSHG    0.004284
 688399.XSHG    0.046474
 Name: ret, Length: 3783, dtype: float64,
 Timestamp('2020-02-25 00:00:00'): order_book_id
 000001.XSHE   -0.012475
 000002.XSHE    0.014879
 000004.XSHE    0.100000
 000005.XSHE   -0.017241
 000006.XSHE   -0.016598
                  ...
 688369.XSHG    0.014511
 688388.XSHG    0.027046
 688389.XSHG    0.027381
 688398.XSHG    0.011472
 688399.XSHG    0.044410
 Name: ret, Length: 3785, dtype: float64,
 Timestamp('2020-02-26 00:00:00'): order_book_id
 000001.XSHE   -0.003324
 000002.XSHE    0.026594
 000004.XSHE   -0.100048
 000005.XSHE    0.045614
 000006.XSHE    0.021097
                  ...
 688369.XSHG   -0.036835
 688388.XSHG   -0.092910
 688389.XSHG   -0.111626
 688398.XSHG   -0.019049
 688399.XSHG   -0.049252
 Name: ret, Length: 3787, dtype: float64,
 Timestamp('2020-02-27 00:00:00'): order_book_id
 000001.XSHE    0.008005
 000002.XSHE   -0.014613
 000004.XSHE   -0.011224
 000005.XSHE   -0.016779
 000006.XSHE   -0.010331
                  ...
 688369.XSHG    0.068866
 688388.XSHG    0.000149
 688389.XSHG   -0.020435
 688398.XSHG   -0.054106
 688399.XSHG   -0.023711
 Name: ret, Length: 3787, dtype: float64,
 Timestamp('2020-02-28 00:00:00'): order_book_id
 000001.XSHE   -0.040371
 000002.XSHE   -0.002696
 000004.XSHE    0.100000
 000005.XSHE   -0.047782
 000006.XSHE   -0.033403
                  ...
 688369.XSHG   -0.051887
 688388.XSHG   -0.102411
 688389.XSHG    0.003995
 688398.XSHG   -0.091052
 688399.XSHG    0.099217
 Name: ret, Length: 3788, dtype: float64,
 Timestamp('2020-03-02 00:00:00'): order_book_id
 000001.XSHE    0.020000
 000002.XSHE    0.052045
 000004.XSHE    0.100000
 000005.XSHE    0.032258
 000006.XSHE    0.041037
                  ...
 688369.XSHG    0.034237
 688388.XSHG    0.042952
 688389.XSHG    0.025641
 688398.XSHG    0.051724
 688399.XSHG   -0.021675
 Name: ret, Length: 3790, dtype: float64,
 Timestamp('2020-03-03 00:00:00'): order_book_id
 000001.XSHE   -0.004733
 000002.XSHE   -0.000964
 000004.XSHE   -0.055171
 000005.XSHE    0.024306
 000006.XSHE    0.049793
                  ...
 688369.XSHG    0.025580
 688388.XSHG    0.003816
 688389.XSHG   -0.004310
 688398.XSHG   -0.008525
 688399.XSHG    0.001820
 Name: ret, Length: 3790, dtype: float64,
 Timestamp('2020-03-04 00:00:00'): order_book_id
 000001.XSHE   -0.002038
 000002.XSHE    0.037299
 000004.XSHE    0.038534
 000005.XSHE    0.037288
 000006.XSHE    0.007905
                  ...
 688369.XSHG   -0.004279
 688388.XSHG    0.001267
 688389.XSHG   -0.027273
 688398.XSHG    0.025132
 688399.XSHG   -0.027885
 Name: ret, Length: 3790, dtype: float64,
 Timestamp('2020-03-05 00:00:00'): order_book_id
 000001.XSHE    0.047651
 000002.XSHE    0.001240
 000004.XSHE   -0.048486
 000005.XSHE    0.003268
 000006.XSHE   -0.001961
                  ...
 688369.XSHG   -0.026154
 688388.XSHG    0.022307
 688389.XSHG   -0.011571
 688398.XSHG   -0.004677
 688399.XSHG   -0.019123
 Name: ret, Length: 3793, dtype: float64,
 Timestamp('2020-03-06 00:00:00'): order_book_id
 000001.XSHE   -0.023392
 000002.XSHE   -0.036223
 000004.XSHE    0.002392
 000005.XSHE   -0.006515
 000006.XSHE   -0.027505
                  ...
 688369.XSHG   -0.045770
 688388.XSHG    0.020582
 688389.XSHG    0.012157
 688398.XSHG   -0.000810
 688399.XSHG    0.005602
 Name: ret, Length: 3794, dtype: float64,
 Timestamp('2020-03-09 00:00:00'): order_book_id
 000001.XSHE   -0.038589
 000002.XSHE   -0.018632
 000004.XSHE   -0.047971
 000005.XSHE   -0.006557
 000006.XSHE   -0.030303
                  ...
 688369.XSHG   -0.073071
 688388.XSHG   -0.090220
 688389.XSHG   -0.003559
 688398.XSHG   -0.051735
 688399.XSHG   -0.077103
 Name: ret, Length: 3794, dtype: float64,
 Timestamp('2020-03-10 00:00:00'): order_book_id
 000001.XSHE    0.021453
 000002.XSHE    0.008183
 000004.XSHE    0.023314
 000005.XSHE    0.013201
 000006.XSHE    0.010417
                  ...
 688369.XSHG    0.041768
 688388.XSHG    0.075000
 688389.XSHG   -0.034821
 688398.XSHG    0.010946
 688399.XSHG   -0.028130
 Name: ret, Length: 3796, dtype: float64,
 Timestamp('2020-03-11 00:00:00'): order_book_id
 000001.XSHE   -0.004743
 000002.XSHE   -0.013636
 000004.XSHE   -0.027683
 000005.XSHE    0.006515
 000006.XSHE    0.006186
                  ...
 688388.XSHG   -0.016124
 688389.XSHG   -0.018501
 688396.XSHG   -0.060519
 688398.XSHG   -0.014042
 688399.XSHG    0.005093
 Name: ret, Length: 3797, dtype: float64,
 Timestamp('2020-03-12 00:00:00'): order_book_id
 000001.XSHE   -0.000681
 000002.XSHE   -0.014154
 000004.XSHE   -0.032250
 000005.XSHE   -0.038835
 000006.XSHE   -0.022541
                  ...
 688388.XSHG   -0.037346
 688389.XSHG   -0.020735
 688396.XSHG   -0.003775
 688398.XSHG   -0.024194
 688399.XSHG    0.075269
 Name: ret, Length: 3797, dtype: float64,
 Timestamp('2020-03-13 00:00:00'): order_book_id
 000001.XSHE   -0.010899
 000002.XSHE   -0.016694
 000004.XSHE   -0.010935
 000005.XSHE   -0.010101
 000006.XSHE    0.002096
                  ...
 688388.XSHG   -0.018006
 688389.XSHG   -0.049567
 688396.XSHG    0.019185
 688398.XSHG   -0.048532
 688399.XSHG   -0.034483
 Name: ret, Length: 3798, dtype: float64,
 Timestamp('2020-03-16 00:00:00'): order_book_id
 000001.XSHE   -0.053030
 000002.XSHE   -0.030900
 000004.XSHE   -0.065544
 000005.XSHE   -0.023810
 000006.XSHE   -0.006276
                  ...
 688388.XSHG   -0.053176
 688389.XSHG   -0.030380
 688396.XSHG   -0.040205
 688398.XSHG   -0.046757
 688399.XSHG   -0.028690
 Name: ret, Length: 3798, dtype: float64,
 Timestamp('2020-03-17 00:00:00'): order_book_id
 000001.XSHE   -0.024727
 000002.XSHE   -0.015067
 000004.XSHE    0.001690
 000005.XSHE   -0.006969
 000006.XSHE   -0.014737
                  ...
 688388.XSHG   -0.014085
 688389.XSHG   -0.023499
 688396.XSHG    0.033898
 688398.XSHG   -0.039356
 688399.XSHG   -0.057850
 Name: ret, Length: 3798, dtype: float64,
 Timestamp('2020-03-18 00:00:00'): order_book_id
 000001.XSHE   -0.052200
 000002.XSHE   -0.064390
 000004.XSHE   -0.030090
 000005.XSHE    0.017544
 000006.XSHE   -0.023504
                  ...
 688388.XSHG    0.000536
 688389.XSHG   -0.018182
 688396.XSHG   -0.033958
 688398.XSHG   -0.033300
 688399.XSHG   -0.011318
 Name: ret, Length: 3798, dtype: float64,
 Timestamp('2020-03-19 00:00:00'): order_book_id
 000001.XSHE   -0.037766
 000002.XSHE   -0.040684
 000004.XSHE    0.024935
 000005.XSHE   -0.027586
 000006.XSHE    0.000000
                  ...
 688388.XSHG    0.001606
 688389.XSHG    0.018519
 688396.XSHG    0.018424
 688398.XSHG   -0.002088
 688399.XSHG   -0.033553
 Name: ret, Length: 3799, dtype: float64,
 Timestamp('2020-03-20 00:00:00'): order_book_id
 000001.XSHE    0.023712
 000002.XSHE    0.022592
 000004.XSHE   -0.024045
 000005.XSHE    0.010638
 000006.XSHE    0.010941
                  ...
 688388.XSHG   -0.022986
 688389.XSHG    0.019786
 688396.XSHG   -0.025232
 688398.XSHG    0.028452
 688399.XSHG    0.053097
 Name: ret, Length: 3799, dtype: float64,
 Timestamp('2020-03-23 00:00:00'): order_book_id
 000001.XSHE   -0.029553
 000002.XSHE   -0.048450
 000004.XSHE   -0.063768
 000005.XSHE   -0.024561
 000006.XSHE   -0.036797
                  ...
 688388.XSHG   -0.136786
 688389.XSHG    0.020975
 688396.XSHG   -0.129182
 688398.XSHG    0.000203
 688399.XSHG   -0.012282
 Name: ret, Length: 3800, dtype: float64,
 Timestamp('2020-03-24 00:00:00'): order_book_id
 000001.XSHE    0.037860
 000002.XSHE    0.014257
 000004.XSHE    0.024768
 000005.XSHE    0.014388
 000006.XSHE    0.015730
                  ...
 688388.XSHG    0.017114
 688389.XSHG    0.032357
 688396.XSHG    0.011497
 688398.XSHG    0.021965
 688399.XSHG   -0.005497
 Name: ret, Length: 3800, dtype: float64,
 Timestamp('2020-03-25 00:00:00'): order_book_id
 000001.XSHE    0.020619
 000002.XSHE    0.064257
 000004.XSHE    0.013293
 000005.XSHE    0.021277
 000006.XSHE    0.024336
                  ...
 688388.XSHG    0.037599
 688389.XSHG    0.014428
 688396.XSHG    0.007763
 688398.XSHG    0.016517
 688399.XSHG    0.052645
 Name: ret, Length: 3802, dtype: float64,
 Timestamp('2020-03-26 00:00:00'): order_book_id
 000001.XSHE    0.014763
 000002.XSHE   -0.011321
 000004.XSHE   -0.018187
 000005.XSHE   -0.010417
 000006.XSHE   -0.019438
                  ...
 688388.XSHG   -0.029029
 688389.XSHG    0.052477
 688396.XSHG   -0.024759
 688398.XSHG   -0.050509
 688399.XSHG    0.041510
 Name: ret, Length: 3803, dtype: float64,